In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan,4],
                   'B':[5,np.nan, np.nan, 8],
                   'C':[10,20,30,40]
})

In [3]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [6]:
df.dropna(axis=1,thresh=2)

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  NaN  NaN  30
3  4.0  8.0  40

In [7]:
df.fillna(value='UNE VALEUR')

            A           B   C
0           1           5  10
1           2  UNE VALEUR  20
2  UNE VALEUR  UNE VALEUR  30
3           4           8  40

In [8]:
df.fillna(value=0)

     A    B   C
0  1.0  5.0  10
1  2.0  0.0  20
2  0.0  0.0  30
3  4.0  8.0  40

In [10]:
df['A']=df['A'].fillna(value=0)

In [11]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  NaN  20
2  0.0  NaN  30
3  4.0  8.0  40

In [12]:
df['B'].mean()

6.5

In [13]:
df['B']=df['B'].fillna(value=df['B'].mean())

In [14]:
df

     A    B   C
0  1.0  5.0  10
1  2.0  6.5  20
2  0.0  6.5  30
3  4.0  8.0  40